services:
  authly:
    build: .
    container_name: authly-app
    ports:
      - "${HTTP_PORT:-8080}:80"
      #- "${HTTPS_PORT:-8443}:443"
      - "${METRICS_PORT:-9090}:9090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_URLS=http://+:80;https://+:443
      
      # Application Settings
      - AUTHLY_NAME=${AUTHLY_NAME:-Authly}
      - AUTHLY_DOMAIN=${AUTHLY_DOMAIN}
      - AUTHLY_BASE_URL=${AUTHLY_BASE_URL:-localhost:80}
      - AUTHLY_VERSION=${AUTHLY_VERSION:-1.0.0}
      - AUTHLY_DEBUG_LOGGING=${AUTHLY_DEBUG_LOGGING:-false}
      - AUTHLY_ENABLE_METRICS=${AUTHLY_ENABLE_METRICS:-true}
      
      # External OAuth Configuration
      - AUTHLY_ENABLE_GOOGLE=${AUTHLY_ENABLE_GOOGLE:-false}
      - AUTHLY_ENABLE_MICROSOFT=${AUTHLY_ENABLE_MICROSOFT:-false}
      - AUTHLY_ENABLE_GITHUB=${AUTHLY_ENABLE_GITHUB:-false}
      - AUTHLY_ENABLE_FACEBOOK=${AUTHLY_ENABLE_FACEBOOK:-false}
      
      # Google OAuth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID:-}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET:-}
      
      # Microsoft OAuth
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID:-}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET:-}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID:-common}
      
      # GitHub OAuth
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      
      # Facebook OAuth
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID:-}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET:-}
      
      # User Lockout Security Configuration
      - AUTHLY_USER_LOCKOUT_ENABLED=${AUTHLY_USER_LOCKOUT_ENABLED:-true}
      - AUTHLY_USER_LOCKOUT_MAX_ATTEMPTS=${AUTHLY_USER_LOCKOUT_MAX_ATTEMPTS:-3}
      - AUTHLY_USER_LOCKOUT_DURATION=${AUTHLY_USER_LOCKOUT_DURATION:-30}
      - AUTHLY_USER_LOCKOUT_SLIDING_WINDOW=${AUTHLY_USER_LOCKOUT_SLIDING_WINDOW:-true}
      - AUTHLY_USER_LOCKOUT_WINDOW=${AUTHLY_USER_LOCKOUT_WINDOW:-15}
      
      # IP Rate Limiting Configuration
      - AUTHLY_IP_RATE_LIMIT_ENABLED=${AUTHLY_IP_RATE_LIMIT_ENABLED:-true}
      - AUTHLY_IP_RATE_LIMIT_MAX_ATTEMPTS=${AUTHLY_IP_RATE_LIMIT_MAX_ATTEMPTS:-5}
      - AUTHLY_IP_RATE_LIMIT_BAN_DURATION=${AUTHLY_IP_RATE_LIMIT_BAN_DURATION:-60}
      - AUTHLY_IP_RATE_LIMIT_SLIDING_WINDOW=${AUTHLY_IP_RATE_LIMIT_SLIDING_WINDOW:-false}
      - AUTHLY_IP_RATE_LIMIT_WINDOW=${AUTHLY_IP_RATE_LIMIT_WINDOW:-30}
      
    volumes:
      - ./data:/app/wwwroot/data
      - ./keys:/root/.aspnet/DataProtection-Keys
      
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80/health/ready || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 30s
      
    networks:
      - authly-network
    restart: unless-stopped

  healthcheck-ui:
    image: xabarilcoding/healthchecksui:latest
    container_name: authly-healthcheck-ui
    ports:
      - "${HEALTHCHECK_UI_PORT:-8090}:80"
    environment:
      - HealthChecksUI__HealthChecks__0__Name=Authly Application
      - HealthChecksUI__HealthChecks__0__Uri=http://authly:80/health
      - HealthChecksUI__HealthChecks__1__Name=Authly Readiness
      - HealthChecksUI__HealthChecks__1__Uri=http://authly:80/health/ready
      - HealthChecksUI__HealthChecks__2__Name=Authly Liveness
      - HealthChecksUI__HealthChecks__2__Uri=http://authly:80/health/live
    volumes:
      - ./healthchecksui.json:/app/healthchecksui.json:ro
    depends_on:
      authly:
        condition: service_healthy
    networks:
      - authly-network
    restart: unless-stopped

networks:
  authly-network:
    driver: bridge